[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "klubradio-scraper"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []  # wir nutzen requirements.txt

[tool.pytest.ini_options]
addopts = "-q"
python_files = ["test_*.py"]
