name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff
          pip install -e .

      - name: Ruff
        run: ruff check .

      - name: Run unit + integration tests (offline)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q

  supabase_live:
    runs-on: ubuntu-latest
    needs: lint_and_tests
    if: ${{ github.event_name != 'pull_request' }}  # Live-Upload nicht bei PRs
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run Supabase live smoke test
        env:
          PYTHONPATH: ${{ github.workspace }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: pytest -q tests/test_supabase_live.py
